export const LANDING = '/';
export const HOME = '/home/:date';
export const STANDINGS = '/standings';
export const FAVORITES = '/favorites';
export const FAVORITES_EDIT ='/favorites/edit'
export const BOXSCORE = '/games/:date/:id';
export const SIGNIN = '/auth/signIn';

export const BACKOFFICE_LANDING = '/admin';
export const BACKOFFICE_DASHBOARD = '/admin/dashboard';
export const BACKOFFICE_UPLOAD= '/admin/upload';
export const BACKOFFICE_EDIT_GAMEDAYS= '/admin/edit/gamedays';
export const BACKOFFICE_MODIFY_GAMEDAYS= '/admin/edit/gamedays/:id/';
export const BACKOFFICE_EDIT_TEAMS= '/admin/edit/teams';
export const BACKOFFICE_MODIFY_TEAMS= '/admin/edit/teams/:id/';
export const BACKOFFICE_EDIT_STANDINGS= '/admin/edit/standings';
export const BACKOFFICE_EDIT_USERS= '/admin/edit/users';
export const BACKOFFICE_MODIFY_USERS= '/admin/edit/users/:id/';
export const BACKOFFICE_EDIT_BOXSCORE = '/admin/edit/boxscore';
